### ISSUE TITLE
How to start the extension?

### ISSUE THREAD

**Issue by MirrorMinus** [slidevjs/slidev-vscode#12]
(Sorry, My English isn't very well)
After I downloaded this extension, I found I couldn't find the way to start it. the side panel only gave me the markdown mode document.
I have downloaded the Node.js and slidev.
<img width="942" alt="屏幕截图 2022-01-28 115958" src="https://user-images.githubusercontent.com/70083920/151485514-3f4c3763-bb49-4ec0-810e-6c3eb6aae854.png">
<img width="322" alt="屏幕截图 2022-01-28 120801" src="https://user-images.githubusercontent.com/70083920/151485752-699407c7-d8e2-4a19-b787-8cc78480634c.png">

**Comment by lucacorbucci** [comment]
Hi, have you seen this issue? https://github.com/slidevjs/slidev-vscode/issues/10
