### ISSUE TITLE
Why the icon didn't show up in my VScode primary sidebar?

### ISSUE THREAD

**Issue by zzx58-027** [slidevjs/slidev-vscode#14]
<img width="836" alt="image" src="https://user-images.githubusercontent.com/77034104/162261606-834bba63-bde6-46ba-9b83-a0fb6241d9f4.png">
<img width="470" alt="image" src="https://user-images.githubusercontent.com/77034104/162261648-ff881889-11bd-4aac-b25a-705e882f2eff.png">

Where is the trigger for the preview?

**Comment by Mickychen00** [comment]
Me too. Did you find the solution?

**Comment by zzx58-027** [comment]
> Me too. Did you find the solution?

Yes, the problem is that my workplace didn't automatically enable this feature, check your Extension and set this feature to recommend for this workspace.  That should work.

**Comment by Mickychen00** [comment]
> > Me too. Did you find the solution?
> 
> Yes, the problem is that my workplace didn't automatically enable this feature, check your Extension and set this feature to recommend for this workspace. That should work.

Thank you!, It works!

**Comment by zzx58-027** [comment]
Great. Enjoy!

**Comment by CatCodeMe** [comment]
> 

what can I do ? don't work
![image](https://user-images.githubusercontent.com/11496772/184835460-e5234746-4e7f-44b4-98ae-d562fc445ae8.png)

**Comment by zzx58-027** [comment]
> > 
> 
> what can I do ? don't work ![image](https://user-images.githubusercontent.com/11496772/184835460-e5234746-4e7f-44b4-98ae-d562fc445ae8.png)

specific the problem you meet please.

**Comment by CatCodeMe** [comment]
> > > 
> > 
> > 
> > what can I do ? don't work ![image](https://user-images.githubusercontent.com/11496772/184835460-e5234746-4e7f-44b4-98ae-d562fc445ae8.png)
> 
> specific the problem you meet please.

thanks, I have fix this problem.

**Comment by CatCodeMe** [comment]
Before

> > > > 
> > > 
> > > 
> > > what can I do ? don't work ![image](https://user-images.githubusercontent.com/11496772/184835460-e5234746-4e7f-44b4-98ae-d562fc445ae8.png)
> > 
> > 
> > specific the problem you meet please.
> 
> thanks, I have fix this problem.

Before,  I  create a dir with xx.md , there is no icon in ther sidebar; like this
![image](https://user-images.githubusercontent.com/11496772/185017953-759d47d0-966f-4585-acf8-89e075c35dda.png)

- I have to use `slidev -p {any no conflict port}  ppt.md` (has install slidev globally),  and open with browser

After, I use `npm init slidev` in this dir,  then  go to sub dir `slidev`(default name),  **reopen `slidev`  dir with vscode**,  it works
![image](https://user-images.githubusercontent.com/11496772/185018819-0d82fb76-0e4d-478f-80a3-43cce07829df.png)

- Tips
- use some no conflict port (default is 3030), change in vscode config; 
![image](https://user-images.githubusercontent.com/11496772/185019206-7e3c5f3a-69e1-462d-916c-7b477746d84d.png)
- preview don't work , start `slidev -p {port}  {xx.md}`, then refresh preview icon
- 
![image](https://user-images.githubusercontent.com/11496772/185019686-2a23ad53-0824-4698-8387-fe71205fcc09.png)


finally,  it isn't friendlly to plain user.

**Comment by Mickychen00** [comment]
For me, the preview doesn't work both inside the dir or the subdir. Surely not user-friendly extension.
