### ISSUE TITLE
Command not found

### ISSUE THREAD

**Issue by ZionDeng** [slidevjs/slidev-vscode#15]
* I installed Slidev Plugin in Vscode, I got the following error. 
![image](https://user-images.githubusercontent.com/47084312/173189445-af7865c5-482c-4133-9b11-cd3af7eac94e.png)
* I force enabled the entension. Also, I cannot find the extension icon on the left side bar as shown in the demo. 

I am using windows. And I have upgraded to the latest version

**Comment by hongyonghan** [comment]
i also.

**Comment by ChiMaoShuPhy** [comment]
@ZionDeng Did you find a solution or workaround? In my case the extension is activated and appears in the side bar, some of the function works (such as convert to html), but no slide preview panel and focus-side-panel command leads to a similar error as yours. I update @slidev/cli to 0.35.5 and this issue suddenly appears

**Comment by gy-mate** [comment]
Similar error on macOS:
<img width="277" alt="Screenshot 2024-04-25 at 00 24 25" src="https://github.com/slidevjs/slidev-vscode/assets/13014176/0de91a91-170a-432a-867b-ecf540ff5abc">

**Comment by kermanx** [comment]
We've rewritten the VSCode extension for Slidev (https://github.com/slidevjs/slidev/pull/1557). Upgrading the VSCode extension to the latest (`0.49.1`) can fix this issue.
