### ISSUE TITLE
Preview does not work

### ISSUE THREAD

**Issue by ChiMaoShuPhy** [slidevjs/slidev-vscode#16]
I update @slidev/cli to v0.35.5, installed globally and slidev-vscode is 0.4.0. 

The .md file is in the project root, I also have @slidev/cli dep in project root pakcage.json. The slide could be open in browser. Slidev extension icon also appears in the activity bar. `Convert current selection to HTML` works fine, `Show slidev` and `Go to previous slide` works fine.

However, The preview panel did not show up and `Command 'Slidev: Focus side panel' resulted in an error (command 'slidev.focus-side-panel' not found)`  and `Command 'Slidev: Move slide up resulted in an error (Cannot read properties of undefined (reading 'info'))`, `Move slide down` results in the same error as `Move slide up`.

**Comment by leon-ziya** [comment]
SLIDEV extension icon not appearing in activity bar
![image](https://user-images.githubusercontent.com/29588786/222650035-1a2dc44e-62b5-4736-bb0c-c1d7f5a6f93f.png)

**Comment by Fanisting** [comment]
I have the similar problem!

**Comment by wq24** [comment]
I have the same problem!Have you solved it?

**Comment by ChiMaoShuPhy** [comment]
> I have the same problem!Have you solved it?

Actually I have switched to using Marp.  I stopped searching for a fix but this issue got accidentally fixed after an OS re-installation.

**Comment by FrancescoSaverioZuppichini** [comment]
same here

**Comment by kermanx** [comment]
This is because Slidev cannot make sure it is a "Slidev Markdown" or a common markdown when there is no `package.json` indicating this. A simpler workaround could be setting `slidev.enabled` to `true` in the workspace settings.

**Comment by kermanx** [comment]
We've rewritten the VSCode extension for Slidev (https://github.com/slidevjs/slidev/pull/1557). Upgrading the VSCode extension to the latest (`0.49.1`) can fix this issue.
