### ISSUE TITLE
SLIDEV extension icon not appearing in activity bar

### ISSUE THREAD

**Issue by leon-ziya** [slidevjs/slidev-vscode#19]
please help me!
SLIDEV extension icon not appearing in activity bar
SLIDEV扩展图标未出现在活动栏中
![image](https://user-images.githubusercontent.com/29588786/222650164-de3504f2-6377-4fe5-8cfa-6ca5d0cbc92a.png)

How can this be resolved！

**Comment by Fanisting** [comment]
我尝试过使用vs code preview，有一段时间是可以使用的，但后来又不行了

**Comment by MicroBlueee** [comment]
Same problem and the commands do not work either
![image](https://user-images.githubusercontent.com/49147382/229413435-ae330d2f-ea91-4e0a-81c0-ba0e5578d7ed.png)

**Comment by shoalna** [comment]
Instead of opening the markdown file, use the "Open Folder" in vs code to open the project folder.
See https://github.com/slidevjs/slidev-vscode/issues/14

**Comment by jxpeng98** [comment]
你需要现在本地安装project文件夹
```
npm init slidev@latest
```

接下来直接打开生成的slidev的文件夹，slidev的图标会显示在侧边栏。在之后你在当前workspace添加你的文件或者文件夹就可以了。

**Comment by kermanx** [comment]
We've rewritten the VSCode extension for Slidev (https://github.com/slidevjs/slidev/pull/1557). Upgrading the VSCode extension to the latest (`0.49.1`) can fix this issue.
