### ISSUE TITLE
Feature: Auto-Focus `<v-click>` Elements

### ISSUE THREAD

**Issue by CodeMan99** [slidevjs/slidev-vscode#20]
I love that the preview follows my cursor while editing `slides.md`.

Please add the same for `<v-click>` elements.

**Comment by kermanx** [comment]
This is a nice feature, but I am afraid that this can be quite hard to implement. And we've rewritten the VSCode extension for Slidev (https://github.com/slidevjs/slidev/pull/1557). Close this for now.
