### ISSUE TITLE
command 'slidev.preview-refresh' not found

### ISSUE THREAD

**Issue by FrancescoSaverioZuppichini** [slidevjs/slidev-vscode#23]
Hi there :wave:

I've installed globally

```bash
npm i -g @slidev/cli
```

Then the extension but I got this error

<img width="293" alt="Screenshot 2024-03-07 at 23 00 33" src="https://github.com/slidevjs/slidev-vscode/assets/15908060/f4b60014-bfd5-439c-9688-f59af05758fd">

Thanks a lot 🤗 

Fra

**Comment by yu45020** [comment]
Same here. Installed globally but no preview. I then install manually following this [instruction](https://sli.dev/guide/install#install-manually), and it works, and it works in vs code. 

A simple fix: copy `package.json` to any folder with a markdown file. The extension works again. The two files can be generated by `npm install @slidev/cli @slidev/theme-default`

`package.json` file content
```json
{
  "dependencies": {
    "@slidev/cli": "^0.49.0-beta.3",
    "@slidev/theme-default": "^0.25.0"
  }
}
```

**Comment by kermanx** [comment]
This is because Slidev cannot make sure it is a "Slidev Markdown" or a common markdown when there is no `package.json` indicating this. A simpler workaround could be setting `slidev.enabled` to `true` in the workspace settings.

**Comment by kermanx** [comment]
We've rewritten the VSCode extension for Slidev (https://github.com/slidevjs/slidev/pull/1557). Upgrading the VSCode extension to the latest (`0.49.1`) can fix this issue.
