### ISSUE TITLE
Allow specifying a subdir for slidev

### ISSUE THREAD

**Issue by mdbenito** [slidevjs/slidev-vscode#24]
Currently slidev expects a `package.json` in the root of the repository. However, some projects which might not be js-based and use sli.dev for slides in a subfolder, won't have this. It would be very convenient to be able to tell the extension where to find the slides. 

I have tried forcing `"slidev.enabled": true` in the workspace settings, but this has no effect.

Of course, opening that folder instead of the project root in vscode solves the problem.

Thanks for the extension!

**Comment by kermanx** [comment]
We've rewritten the VSCode extension for Slidev (https://github.com/slidevjs/slidev/pull/1557). Upgrading the VSCode extension to the latest (`0.49.1`) can resolve this issue.
