### ISSUE TITLE
Question: No Slidev icon in activity bar

### ISSUE THREAD

**Issue by NN708** [slidevjs/slidev-vscode#4]
Hello everyone, I installed this from VS Code extensions, but saw no Slidev icon in the activity bar. May I ask how can I use this extension?

Extension version: 0.2.0
VS Code version: 1.56.2

**Comment by antfu** [comment]
It will search for the `@slidev/cli` dependencies in your project root

**Comment by NN708** [comment]
Thanks for your help! I think I have already installed it manually following [Installation -> Install Manually](https://sli.dev/guide/install.html#install-manually). I can run it correctly from the command line.

**Comment by NN708** [comment]
I found that the problem is caused by not having a `package.json` file. In [index.ts line 13](https://github.com/slidevjs/slidev-vscode/blob/36fb2c95aff8b456a668b859f6c9047837820efc/src/index.ts#L13), the extension uses the `package.json` file to determine whether `@slidev/cli` is installed. Thanks again for your help!

However, I think this also means when Slidev is installed globally, the extension can't work normally. Maybe an alternative method should be used to find the `@slidev/cli` installation?

**Comment by antfu** [comment]
Now in v0.3.0 you can force enable the extension without the deps check:

```jsonc
{
  "slidev.enabled": true
}
```

**Comment by matthiasg** [comment]
Does slidev look recursively upwards from the markdown file ? For use in monorepos

**Comment by pytimer** [comment]
@antfu I install slidev vscode extension, but no slidev icon. I install slidev-cli globally. 

vscode version: 1.63.0
slidev version: 0.27.18
