### ISSUE TITLE
Update documentation for use of this extension

### ISSUE THREAD

**Issue by sugatoray** [slidevjs/slidev-vscode#5]
Please add some documentation with at least a few figures and a quick GIF demo to make it clear, what is required to use this vscode extension and how to use it.

**Comment by nullgit** [comment]
Press `Ctrl + Shift + P`, enter `slidev`, and click `View: Show Slidev`

**Comment by CatCodeMe** [comment]
> 

don't have this option and icon after install 0.4.0

**Comment by stefandeml** [comment]
yeah, extension seems to be broken. Better to withdraw from marketplace...

**Comment by stefandeml** [comment]
you need to select "View: Show Slidev"

**Comment by piranna** [comment]
I find it easier to have an icon at the top-right of the editor when detecting a Slidev document... Maybe it can be done if it's a .md file and has a frontmatter.

**Comment by piranna** [comment]
But yeah, at least add this info about how to enable it to the readme.

**Comment by piranna** [comment]
In any case, the extension is not working for me either.

**Comment by Fanisting** [comment]
In any case, the extension is not working for me neither.

**Comment by Giuseppe499** [comment]
It is not working also for me
