### ISSUE TITLE
bug: Focus side panel resulted in an error

### ISSUE THREAD

**Issue by Decipher** [slidevjs/slidev-vscode#7]
**Describe the bug**
**Focus side panel** results in an error.

**To Reproduce**
1. Install Slidev extension
2. Open command pallete
3. Select: **Slidev: Focus side panel**

**Expected behavior**
Focus side panel.

**Media**
![image](https://user-images.githubusercontent.com/161090/123021343-444a7a00-d417-11eb-84b6-5efc70121e0a.png)

**Comment by cyberbibby** [comment]
Me too.

**Comment by Decipher** [comment]
This appears to have resolved for me.

How about you @cyberbibby?

**Comment by JounQin** [comment]
@antfu It seems this plugin not working with VSCode workspace, right?

**Comment by kermanx** [comment]
We've rewritten the VSCode extension for Slidev (https://github.com/slidevjs/slidev/pull/1557). Upgrading the VSCode extension to the latest (`0.49.1`) can fix this issue.
